### ISSUE TITLE
Incorrect radio button number order for trainer feedback

### ISSUE THREAD

**Issue by andrewjackson95** [QAC-Portal/QA-Portal#74]
The order for the radio buttons in the Trainer - Course Feedback page is in the wrong order, displaying from 9 - 1. This should be a database issue, not front end, but will need sorting before deployment. 

![image](https://user-images.githubusercontent.com/56401700/70140476-a8b6b480-168c-11ea-88d5-827e6f7d4944.png)

**Comment by Malverick** [comment]
Needs to be fixed in the database and not on the front end.

**Comment by DALucifer13** [comment]
unable to be fixed without the admin roles issue being fixed, hard changing the database only affects the database file, which is not stored in qa-portal folder

**Comment by Malverick** [comment]
> unable to be fixed without the admin roles issue being fixed, hard changing the database only affects the database file, which is not stored in qa-portal folder. 

You can fix it on front end with

**Comment by z9170qa** [comment]
The issue here can be easily fixed by the admin. The radio button number labels are going backwards just because this is how the radio responses were input in the admin side. Changing them going back to ascending radio button labels and updating the form on the admin side will therefore correct it on the trainer side.
